### ISSUE TITLE
getAccount().getUsername() NPE

### ISSUE THREAD

**Issue by VladBots** [rs-peer/issues#106]
getAccount().getUsername() NPEs.

[SEVERE] Tue Jul 17 21:53:59 EDT 2018: EXCEPTION: SEVEREjava.lang.NullPointerException
	at script.Skeleton.onStart(Skeleton.java:23)
	at org.rspeer.script.Script.start(de:46)
	at org.rspeer.script.11.IIiIIiiiIiIii(ad:100)
	at org.rspeer.ui.80.IIiIIiiiIiIii(hm:225)
	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
	at org.pushingpixels.substance.internal.utils.RolloverButtonListener.mouseReleased(RolloverButtonListener.java:124)
	at java.awt.Component.processMouseEvent(Unknown Source)
	at javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)

**Comment by SPEN-CER** [comment]
Account is null until after onStart. It is set after onStart, unless you've use setAccount prior to that

**Comment by VladBots** [comment]
I use it in onStart to create my antiban profile though!

**Comment by SPEN-CER** [comment]
Regardless, there are other issues with that. What if your script is started while being logged out? I suggest you find another way to create your antiban profile ;)

**Comment by VladBots** [comment]
Good point. Thank you Spencer!

**Comment by VladBots** [comment]
Actually, you need the account to login in anyways, that's why I used that, hmm...

**Comment by SPEN-CER** [comment]
I think it's safe for me to move the account initialization code to a point before onStart is used, I don't remember if there was a reason for me not doing this in the first place
