### ISSUE TITLE
Class def errors when launching multiple clients in quick succession 

### ISSUE THREAD

**Issue by dQw4w9WgXcQ** [rs-peer/issues#17]
[SEVERE] Sun Jun 10 07:26:23 PDT 2018: EXCEPTION: SEVEREjava.lang.NoClassDefFoundError: iy
	at bh.gm(Unknown Source)
	at ai.gu(Unknown Source)
	at ab.iw(Unknown Source)
	at ab.iw(Unknown Source)
	at ai.id(Unknown Source)
	at client.ge(Unknown Source)
	at client.ai(Unknown Source)
	at aj.aw(Unknown Source)
	at aj.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: iy
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 10 more

Error shortly after 1st client logs in when launching 2 or more clients within 30 seconds or so of eachother.

**Comment by SPEN-CER** [comment]
Fixed for the next build
