### ISSUE TITLE
Look & Feel UI Exception

### ISSUE THREAD

**Issue by mswdev** [rs-peer/issues#263]
This has been thrown a few times recently. Doesn't seem to break anything noticable.

> [SEVERE] Fri Oct 26 02:51:07 MDT 2018: EXCEPTION: SEVEREjava.lang.IndexOutOfBoundsException: Index: 440, Size: 440
	at java.util.ArrayList.rangeCheck(ArrayList.java:657)
	at java.util.ArrayList.get(ArrayList.java:433)
	at org.rspeer.ui.30.70.50.iIiiiiiiIIIIi(ce:101)
	at org.rspeer.ui.30.70.50.getElementAt(ce:98)
	at javax.swing.plaf.basic.BasicListUI.updateLayoutState(BasicListUI.java:1360)
	at javax.swing.plaf.basic.BasicListUI.maybeUpdateLayoutState(BasicListUI.java:1311)
	at javax.swing.plaf.basic.BasicListUI.getPreferredSize(BasicListUI.java:578)
	at javax.swing.JComponent.getPreferredSize(JComponent.java:1662)
	at javax.swing.ScrollPaneLayout.layoutContainer(ScrollPaneLayout.java:791)
	at org.pushingpixels.substance.internal.ui.SubstanceScrollPaneUI$AdjustedLayout.layoutContainer(SubstanceScrollPaneUI.java:470)
	at java.awt.Container.layout(Container.java:1511)
	at java.awt.Container.doLayout(Container.java:1500)
	at java.awt.Container.validateTree(Container.java:1696)
	at java.awt.Container.validate(Container.java:1631)
	at javax.swing.RepaintManager$3.run(RepaintManager.java:711)
	at javax.swing.RepaintManager$3.run(RepaintManager.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at javax.swing.RepaintManager.validateInvalidComponents(RepaintManager.java:708)
	at javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1731)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by SPEN-CER** [comment]
When does this happen?

**Comment by Sphiinx** [comment]
> When does this happen?

So far I haven't noticed anything specifically that could be causing it. I'll keep an eye out for what I'm doing when it occurs.

**Comment by Sphiinx** [comment]
Here is another one that is sorta similar under UI. This occurred without any script running, although the Varp Debugger was open and has been working fine for a while.

> [SEVERE] Fri Oct 26 07:27:05 MDT 2018: EXCEPTION: SEVEREjava.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:909)
	at java.util.ArrayList$Itr.next(ArrayList.java:859)
	at org.rspeer.ui.30.70.50.iiiIiiiiiiIIi(ce:54)
	at org.rspeer.ui.30.70.50.iIiiiiiiIIIIi(ce:194)
	at org.rspeer.ui.30.70.20.iIiiiiiiIIIIi(sg:120)
	at org.rspeer.ui.30.70.6.iIiiiiiiIIIIi(vl:63)
	at org.rspeer.ui.30.70.6.run(vl:15)
	at java.lang.Thread.run(Thread.java:748)

**Comment by SPEN-CER** [comment]
Fixed
