### ISSUE TITLE
NPE in rspeer.ui

### ISSUE THREAD

**Issue by josephmr** [rs-peer/issues#275]
Appeared right when a quest creation screen came up, not sure if related.

java.lang.IndexOutOfBoundsException: Index: 7, Size: 7
        at java.util.ArrayList.rangeCheck(ArrayList.java:657)
        at java.util.ArrayList.get(ArrayList.java:433)
        at org.rspeer.ui.3.60.4.IiIIiiiiiiIIi(yl:100)
        at org.rspeer.ui.3.60.4.getElementAt(yl:49)
        at javax.swing.plaf.basic.BasicListUI.updateLayoutState(BasicListUI.java:1360)                                       
        at javax.swing.plaf.basic.BasicListUI.maybeUpdateLayoutState(BasicListUI.java:1311)                                  
        at javax.swing.plaf.basic.BasicListUI.getPreferredSize(BasicListUI.java:578)                                         
        at javax.swing.JComponent.getPreferredSize(JComponent.java:1662)                                                     
        at javax.swing.ScrollPaneLayout.layoutContainer(ScrollPaneLayout.java:791)                                           
        at org.pushingpixels.substance.internal.ui.SubstanceScrollPaneUI$AdjustedLayout.layoutContainer(SubstanceScrollPaneUI.java:470)
        at java.awt.Container.layout(Container.java:1513)
        at java.awt.Container.doLayout(Container.java:1502)
        at java.awt.Container.validateTree(Container.java:1698)                                                              
        at java.awt.Container.validate(Container.java:1633)
        at javax.swing.RepaintManager$3.run(RepaintManager.java:711)                                                         
        at javax.swing.RepaintManager$3.run(RepaintManager.java:709)                                                         
        at java.security.AccessController.doPrivileged(Native Method)                                                        
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)           
        at javax.swing.RepaintManager.validateInvalidComponents(RepaintManager.java:708)                                     
        at javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1731)                                       
        at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)                                                 
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)                                                        
        at java.awt.EventQueue.access$500(EventQueue.java:97)
        at java.awt.EventQueue$3.run(EventQueue.java:709)
        at java.awt.EventQueue$3.run(EventQueue.java:703)
        at java.security.AccessController.doPrivileged(Native Method)                                                        
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)           
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)                                                            
        at org.GNOME.Accessibility.AtkWrapper$6.dispatchEvent(AtkWrapper.java:715)                                           
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)                                 
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)                                    
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)                                 
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)                                             
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)                                              
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by SPEN-CER** [comment]
Fixed for the next build
