### ISSUE TITLE
msg.getSource() throws NullPointerException if player name includes a space

### ISSUE THREAD

**Issue by soccersw2** [rs-peer/issues#277]
As the title states, whenever ChatMessageListener receives a message from a player that has a name with a space, it throws an error:

[SEVERE] Sat Nov 17 20:58:48 CST 2018: EXCEPTION: SEVEREjava.lang.NullPointerException
    at Roulette.notify(Roulette.java:173)
    at org.rspeer.runetek.event.types.ChatMessageEvent.forward(ml:160)
    at org.rspeer.runetek.event.EventDispatcher.immediate(wl:62)
    at org.rspeer.runetek.event.EventMediator.messageReceived(xm:128)
    at ao.l(Unknown Source)
    at fw.f(Unknown Source)
    at client.gz(Unknown Source)
    at client.fk(Unknown Source)
    at client.ad(Unknown Source)
    at ah.ac(Unknown Source)
    at ah.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)

Line 173 is:
Players.getNearest(msg.getSource()).interact("Trade with");

**Comment by soccersw2** [comment]
Replaced whitespace characters to fix.
Players.getNearest(msg.getSource().replace("\u00A0","\u0020")).interact("Trade with");
