### ISSUE TITLE
Can't open client without deleting cache

### ISSUE THREAD

**Issue by aids9345435345kek** [rs-peer/issues#416]
Is there a way to avoid this?

**Comment by Lezor91** [comment]
It would be helpful if you provided more information.

**Comment by adivorcedfork** [comment]
He might be referring to a similar issue to one that I have occasionally...

Every once in a while after I launch a client I get this message repeating. The only way to fix it I've found is to delete the RSPeer folder, restart the launcher, and launch a client...

`Exception in thread "AWT-EventQueue-0"
java.lang.IllegalStateException: Already set!
        at org.rspeer.runetek.providers.subclass.GameCanvas.setCallback(um:6)
        at org.rspeer.ui.component.60.<init>(cl:7)
        at org.rspeer.ui.00.<init>(kk:202)
        at org.rspeer.RSPeer.getView(aq:61)
        at org.rspeer.ui.component.60.IIiiiiiiIiiii(cl:96)
        at org.rspeer.ui.component.60.IIiiiiiiIiiii(cl:282)
        at java.awt.event.InvocationEvent.dispatch(Unknown Source)
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.awt.EventQueue.access$500(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)

        at java.awt.EventQueue$3.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.run(Unknown Source)`

**Comment by aids9345435345kek** [comment]
I haven't ran the launcher with logging to view the specific errors so id kif it's the same one. 

After opening at least one client, all further clients will be launched as java processes only which can be viewed in task mgr, with no visible clients though. It doesn't always happen and sometimes i can open 3 clients but when it does happen (frequently) i have to delete the cache folder. Happens on Windows and  Linux.

Has happened for at least 4 months

**Comment by Lezor91** [comment]
Ok, so maybe you should run the launcher with logging so you can view the specific errors?
