### ISSUE TITLE
Bank#isFull() results in NumberFormatException

### ISSUE THREAD

**Issue by David-Rodden** [rs-peer/issues#422]
Seems like there's a parsing issue with `Bank.isFull()`:
```
java.lang.NumberFormatException: For input string: "The Bank of Gielinor"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:580)
	at java.lang.Integer.valueOf(Integer.java:766)
	at org.rspeer.runetek.api.component.Bank.getCapacity(xo:959)
	at org.rspeer.runetek.api.component.Bank.isFull(xo:686)
```
which prevents from retrieving the value.

**Comment by Lezor91** [comment]
Fixed for the next build.
