### ISSUE TITLE
pose animation def error

### ISSUE THREAD

**Issue by dQw4w9WgXcQ** [rs-peer/issues#53]
java.lang.AbstractMethodError: Method bu.getPoseAnimation()I is abstract
        at bu.getPoseAnimation(Unknown Source)
        at org.rspeer.runetek.adapter.scene.PathingEntity.getPoseAnimation(lm:58)
        at org.dqw4w9wgxcq.scripts.sdn.agility.Agility.notify(Agility.java:34)
        at org.rspeer.runetek.event.types.RenderEvent.forward(wj:86)
        at org.rspeer.runetek.event.EventDispatcher.immediate(io:148)
        at org.rspeer.runetek.event.EventMediator.render(jn:145)
        at ad.l(Unknown Source)
        at ad.w(Unknown Source)
        at client.ai(Unknown Source)
        at aj.aw(Unknown Source)
        at aj.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)

**Comment by SPEN-CER** [comment]
Hi, this is because you are not on the latest build. I've renamed `getPoseAnimation` to `getStance`
