### ISSUE TITLE
World hopper is broken

### ISSUE THREAD

**Issue by Man16** [rs-peer/issues#60]
[SEVERE] Thu Jul 05 16:44:38 BST 2018: EXCEPTION: SEVEREjava.lang.NullPointerException
	at org.rspeer.runetek.api.component.WorldHopper.hopTo(wn:5)
	at org.rspeer.runetek.api.component.WorldHopper.hopTo(wn:170)
	at org.rspeer.runetek.api.component.WorldHopper.randomHop(wn:41)
	at api.worlds.World.hopRandom(World.java:32)
	at script.loop(script.java:170)
	at org.rspeer.script.LoopTask.run(ji:48)
	at org.rspeer.script.Script.run(ol:152)

**Comment by SPEN-CER** [comment]
Fixed
